In [1]:
import numpy as np
from modules import bayesian
from modules import cubicharmonics
import matplotlib.pyplot as plt
import copy

In [2]:
#Carico i dati in data e li ordino in sdata e grid

data=np.transpose(np.loadtxt('tip4p/thermopolarizationresponse.out'))

sdata, grid = bayesian.generatesorteddata(data, 500)

[1. 0. 0.] [0. 0. 1.] [0. 1. 0.]


In [3]:
#Medio i dati su tutti i punti equivalenti per simmetria cubica e 
#ritorno la lista dei nuovi dati 'simmetrizzati' in gplot e sd
C=bayesian.cubicarray(list(grid), True)
dic, dics=bayesian.datadicG(data[1], data[2],cubicharmonics.Gvecgenerateall(500)[1:])
gplot, dataplot1, datasigmaplot1=bayesian.datiplot(C, dic, dics)
#gplot=grid
#dataplot1=sdata[0]
#datasigmaplot1=sdata[1]
dataplot=(dataplot1)
datasigmaplot=datasigmaplot1
sd=np.array([dataplot, datasigmaplot])

numero di elementi:  499
numero cicli teornicamente necessari 373501
numero cicli compiuti 381
numero di elementi non equivalenti per simmetria cubica:  118


In [4]:
#Calcolo il fit bayesiano con glot e sd come test
N=100
mN, SN, y_infer, sy_infer, conta=\
bayesian.bayesianpol(gplot, sd, 8, N, 0.000000001, gplot,bethapar=1, ifprint= True, ifwarning= True, nLbp=0)

parametri ottimali [ 4.76628798e-05  5.93681150e-05 -1.60144700e-04  5.81223422e-04
 -9.73395378e-04  8.68024959e-04 -3.88306776e-04  6.90548930e-05]
numero di armoniche cubiche 8
valore a kmin inferito 4.7953420611037597e-05 bias 4.7662879844493085e-05 dato a kmin 4.849114344202728e-05
determinante matrice delle armoniche cubiche ridotte: 1.0320122787248792e+93


In [5]:
#Plotto il fit e i dati (gplot e sd)
%matplotlib widget

plt.errorbar(np.linalg.norm(gplot, axis=1)*0.13484622*10, dataplot,datasigmaplot, fmt='.')
plt.fill_between(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer+np.sqrt(sy_infer),y_infer-np.sqrt(sy_infer),  alpha=0.3, color='red')
plt.plot(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer, '.-', color='red')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
#Calcolo il best fit su gplot e sd con 50 dati
N=100
mN, SN, y_infer, sy_infer, spar, log_evidence_vP=\
bayesian.bestfit(gplot, sd, N, gplot, ifbetha=False, ifprintbestfit= False, ifprintfinal= True, nLbf=0)
#Plotto il best fit e i dati (gplot e sd)



%matplotlib widget

plt.fill_between(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer+np.sqrt(sy_infer-1), y_infer-np.sqrt(sy_infer-1),  alpha=0.3, color='red')
plt.plot(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer, '.-', color='red')
plt.errorbar(np.linalg.norm(gplot, axis=1)*0.13484622*10, dataplot,datasigmaplot, fmt='.')

parametri ottimali [ 4.78673337e-05  3.70071260e-05  1.57968353e-05 -4.25093719e-06
  6.65299301e-06]
numero di armoniche cubiche 5
valore a kmin inferito 4.8058623206065244e-05 bias 4.7867333656472196e-05 dato a kmin 4.849114344202728e-05
determinante matrice delle armoniche cubiche ridotte: 5.1435849998963676e+64
grado ottimale 10 grado massimo tentato 28
numero di polinomi nella base ottimale:  5 numero di dati 100
best alpha 1195838330.757022
best betha 1


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<ErrorbarContainer object of 3 artists>

In [7]:
#Plotto la funzione di evidence che ho massimizzato per il best fit nella cella precedente
%matplotlib widget
plt.plot(range(2,(len(log_evidence_vP)+1)*2, 2), log_evidence_vP, '.')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [8]:
#Calcolo il best fit includendo sempre piu' punti 
predbl=[]
spredbl=[]
Npointsbl=[]
N_max=70
N_iter=2
N_min=10
for i in range(1):
    predb=[]
    spredb=[]
    Npointsb=[]
    for N in range(N_min, N_max, N_iter):
        
        mN, SN, y_infer, sy_infer, spar, log_evidence_vP=\
        bayesian.bestfit(gplot, sd, N, gplot, ifbetha=False, ifprintbestfit=False, ifprintfinal=False, nLbf=i)
        Npointsb.append(np.linalg.norm(gplot[N]))
        if (N-N_min)%(((N_max-N_min))//5)==0: print(int((N-N_min)/((N_max-N_min))*100), '%')
        predb.append(mN[0])
        spredb.append(SN[0,0])
        
    predbl.append(predb)
    spredbl.append(spredb)
    Npointsbl.append(Npointsb)

0 %
20 %
40 %
60 %
80 %


In [27]:
#Calcolo il best fit su gplot e sd con 50 dati
N=118
mN, SN, y_infer, sy_infer, spar, log_evidence_vP=\
bayesian.bestfit(gplot, sd, N, gplot, ifbetha=False, ifprintbestfit= False, ifprintfinal= True, nLbf=0)
#Plotto il best fit e i dati (gplot e sd)



%matplotlib widget

plt.fill_between(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer+np.sqrt(sy_infer-1), y_infer-np.sqrt(sy_infer-1),  alpha=0.3, color='red')
plt.plot(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer, '.-', color='red')
plt.errorbar(np.linalg.norm(gplot, axis=1)*0.13484622*10, dataplot,datasigmaplot, fmt='.')

parametri ottimali [ 4.79778586e-05  3.42157994e-05  2.16579226e-05 -8.90921655e-06
  7.88839801e-06]
numero di armoniche cubiche 5
valore a kmin inferito 4.8155369227538384e-05 bias 4.797785863292123e-05 dato a kmin 4.849114344202728e-05
determinante matrice delle armoniche cubiche ridotte: 3.2257058390194626e+67
grado ottimale 10 grado massimo tentato 28
numero di polinomi nella base ottimale:  5 numero di dati 118
best alpha 1211841063.9676661
best betha 1


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<ErrorbarContainer object of 3 artists>

In [28]:
%matplotlib widget
fig, ax=plt.subplots(constrained_layout=True)


plt.rc('font', size=20)          # controls default text sizes
plt.rc('axes', labelsize=20)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=18)    # fontsize of the tick labels
plt.rc('ytick', labelsize=20)    # fontsize of the tick labels
plt.rc('legend', fontsize=20)    # legend fontsize

#ax.set_title('Bayesian best model prediction at $\mathbf{k}=0$ with data in range $[: k_{max}]$')
L=[0,[0,4],[0,4,6], [0,4,6,8], [0,4,6,8,10]]
for i in range(1):
    #ax[0].errorbar(np.array(Npointsbl[i]), np.array(predbl[i]), np.sqrt(np.array(spredbl[i])), fmt='.', label=r'$L_{max}$'+'={}'.format(L[i]))
    ax.errorbar(np.array(Npointsbl[i])*0.13484622*10, (np.array(predbl[i]))*1.0e6, np.sqrt(np.array(spredbl[i]))*1.0e6, fmt='.', color='black')
#ax[0].fill_between(np.array(Npointsbl[0]), np.ones(len(Npointsbl[0]))*0.816-np.ones(len(Npointsbl[0]))*0.021, np.ones(len(Npointsbl[1]))*0.816+np.ones(len(Npointsbl[1]))*0.021, label='GK result', alpha=0.3)    
ax.set_xlabel(r'$k_{max} (nm^{-1})$')
ax.set_ylabel(r'$S(\mathbf{k}=0)\,\left[\frac{\mu V}{K}\right]$')

#plt.savefig('tip4p/predictions.pdf')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, '$S(\\mathbf{k}=0)\\,\\left[\\frac{\\mu V}{K}\\right]$')

In [36]:
%matplotlib widget
fig, ax=plt.subplots(constrained_layout=True)
#ax.set_title('Data')
plt.rc('font', size=20)          # controls default text sizes
plt.rc('axes', labelsize=20)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=18)    # fontsize of the tick labels
plt.rc('ytick', labelsize=20)    # fontsize of the tick labels
plt.rc('legend', fontsize=15)    # legend fontsize
ax.errorbar(np.linalg.norm(gplot, axis=1)*0.13484622*10, dataplot1*1.0e6,datasigmaplot1*1.0e6, fmt='.', color='black') 
#ax[1].fill_between(np.linalg.norm(gplot, axis=1), np.ones(len(gplot))*0.816-np.ones(len(gplot))*0.021, np.ones(len(gplot))*0.816+np.ones(len(gplot))*0.021, label='GK result', alpha=0.3) 
ax.plot(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer*1.0e6 , color='red', label=r'bayesian regression',)
ax.fill_between(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer*1.0e6+np.sqrt(sy_infer-1)*1.0e6, y_infer*1.0e6-np.sqrt(sy_infer-1)*1.0e6,  alpha=0.3, color='red')
ax.set_ylabel(r'$S(\mathbf{k})\, \left[\frac{\mu V}{K}\right]$')
ax.set_xlabel(r'k ($nm^{-1}$)')
ax.set_xlim(0,14)
ax.set_ylim(46,105)
plt.legend()
ax2 = fig.add_axes([0.3, 0.41, 0.43, 0.43])
ax2.set_xlim((1.25,6.5))
ax2.set_ylim((46.8,53))
ax2.set_xticks([2.5,5])
ax2.set_yticks([48, 50, 52])
ax2.plot(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer*1.0e6 , color='red')
ax2.errorbar(np.linalg.norm(gplot, axis=1)*0.13484622*10, dataplot1*1.0e6,datasigmaplot1*1.0e6, fmt='.', color='black')
ax2.fill_between(np.linalg.norm(gplot[:N], axis=1)*0.13484622*10, y_infer*1.0e6+np.sqrt(sy_infer-1)*1.0e6, y_infer*1.0e6-np.sqrt(sy_infer-1)*1.0e6,  alpha=0.3, color='red')
#ax.indicate_inset_zoom(ax2)
#plt.savefig('tip4p/s_wfit.pdf')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [21]:
static=np.transpose(np.loadtxt('tip4p/staticresponse.out')[1:])
static0=np.transpose(np.loadtxt('tip4p/staticresponse.out')[0])

In [22]:
statics, gridst = bayesian.generatesorteddata(static, 500)
C=bayesian.cubicarray(list(gridst), True)
dic, dics=bayesian.datadicG(static[3], static[4],cubicharmonics.Gvecgenerateall(500)[1:])
gplot, dataplotst, datasigmaplotst=bayesian.datiplot(C, dic, dics)


[0. 1. 0.] [1. 0. 0.] [0. 0. 1.]
numero di elementi:  499
numero cicli teornicamente necessari 373501
numero cicli compiuti 381
numero di elementi non equivalenti per simmetria cubica:  118


In [23]:
%matplotlib widget
fig, ax=plt.subplots(1,constrained_layout=True, figsize=[9,9])
ax.errorbar(static[0]*10, static[3], static[4], fmt='.')
ax.errorbar(np.linalg.norm(gplot,axis=1)*0.13484622*10, dataplotst, datasigmaplotst, fmt='.')


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<ErrorbarContainer object of 3 artists>

In [24]:
%matplotlib widget
fig, ax=plt.subplots(constrained_layout=True)
N=46

plt.rc('font', size=20)          # controls default text sizes
plt.rc('axes', labelsize=20)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=20)    # fontsize of the tick labels
plt.rc('ytick', labelsize=20)    # fontsize of the tick labels
plt.rc('legend', fontsize=20)    # legend fontsize
ax.errorbar(np.linalg.norm(gplot[:N],axis=1)*0.13484622*10, 1/(1-dataplotst[:N]), datasigmaplotst[:N]/(1-dataplotst[:N])**2, fmt='.', color='black')
ax.errorbar(np.linalg.norm(gplot[N+3:],axis=1)*0.13484622*10, 1/(1-dataplotst[N+3:]), datasigmaplotst[N+3:]/(1-dataplotst[N+3:])**2, fmt='.', color='black')
ax.errorbar((static0[0]), (static0[3]),static0[4], color='red', label=r'$\epsilon(\mathbf{k}=0)$',fmt='.')
ax.set_xlabel(r'k ($nm^{-1}$)')
ax.set_ylabel(r'$\epsilon(\mathbf{k})$')
ax.legend(loc='best')
ax.set_ylim(ymin=-100, ymax=200)
#plt.savefig('tip4p/epsilonk.pdf')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(-100.0, 200.0)

In [25]:
%matplotlib widget
fig, ax=plt.subplots(constrained_layout=True)

N=46

plt.rc('font', size=20)          # controls default text sizes
plt.rc('axes', labelsize=20)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=20)    # fontsize of the tick labels
plt.rc('ytick', labelsize=20)    # fontsize of the tick labels
plt.rc('legend', fontsize=20)    # legend fontsize


ax.errorbar(np.linalg.norm(gplot,axis=1)*0.13484622*10, dataplotst, datasigmaplotst, fmt='.', color='black')
ax.fill_between(np.linspace(0,15,100), (1-1/static0[3])*np.ones(len(np.linspace(0,15,100)))+ static0[4]/static0[3]**2*np.ones(len(np.linspace(0,15,100))), (1-1/static0[3])*np.ones(len(np.linspace(0,15,100)))- static0[4]/static0[3]**2*np.ones(len(np.linspace(0,15,100))),  alpha=0.2, color='red')
ax.plot(np.linspace(0,15,100), (1-1/static0[3])*np.ones(len(np.linspace(0,15,100))), label=r'$1-\frac{1}{\epsilon(\mathbf{k}=0)}$', color='red')
ax.set_xlabel(r'k ($nm^{-1}$)')
ax.set_ylabel(r'$\chi_c(\mathbf{k})/\epsilon_0$')
ax.legend()
ax.set_xlim(xmin=0, xmax=14)
ax.set_ylim(ymin=0.95, ymax=2.)
ax2 = fig.add_axes([0.3, 0.41, 0.35, 0.33])
ax2.set_xlim((1,5))
ax2.set_ylim((0.98,1.025))
ax2.set_xticks([2.5,5.0])
ax2.set_yticks([0.98,1, 1.02])
ax2.errorbar(np.linalg.norm(gplot,axis=1)*0.13484622*10, dataplotst, datasigmaplotst, fmt='.', color='black')
ax2.fill_between(np.linspace(0,15,100), (1-1/static0[3])*np.ones(len(np.linspace(0,15,100)))+ static0[4]/static0[3]**2*np.ones(len(np.linspace(0,15,100))), (1-1/static0[3])*np.ones(len(np.linspace(0,15,100)))- static0[4]/static0[3]**2*np.ones(len(np.linspace(0,15,100))),  alpha=0.2, color='red')
ax2.plot(np.linspace(0,15,100), (1-1/static0[3])*np.ones(len(np.linspace(0,15,100))), color='red')

static0[3], static0[4]
#plt.savefig('tip4p/epsilonkandchic.pdf')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(63.93857866225694, 1.4010160054120764)

In [25]:
a=[0,1,3]
np.sum(a)
a

[0, 1, 3]

In [82]:
a=np.random.random((256,256))

In [83]:
np.linalg.inv(a)

array([[ 0.28254585, -0.06329333, -0.29136801, ...,  0.26028826,
         0.10693308, -0.48594499],
       [ 0.54260573, -0.18530086, -0.19048543, ..., -0.11876062,
        -0.27087143, -0.39860308],
       [-0.40252451,  0.12039307,  0.30381309, ...,  0.18203124,
         0.17628776,  0.17674521],
       ...,
       [-0.88552165,  0.61350866,  0.29331241, ...,  0.28798447,
         0.63676216,  0.49642839],
       [ 0.09322762, -0.3050202 ,  0.21567828, ..., -0.37954949,
        -0.61957955,  0.35421871],
       [ 0.63110246, -0.38894989, -0.05876909, ..., -0.24810894,
        -0.50844403, -0.29503859]])